package mapper

import (
	"github.com/alterasi/stos/example/source"
	"github.com/alterasi/stos/example/target"
)

// Code generated by STOS [structToStructMapper]
// DO NOT EDIT

type mapperUserImpl struct{}

func NewMapperUserImpl() MapperUser {
	return &mapperUserImpl{}
}

func (impl *mapperUserImpl) Convert(source source.User) target.UserDTO {
	target := target.UserDTO{}
	target.Name = source.Name
	target.Age = source.Age
	target.Gender = source.Gender
	target.Role = source.Role
	target.Birthday = source.Birthday
	return target
}
